[project]
name = "dancarlin"
version = "0.1.0"
description = "A script to download already purchased episodes from dancarlin.com"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
]
